import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Tomasz',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'Test',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: "Example title of product A",
            image: "/images/1611420762665.jpg",
            image2: "/images/1611420821349.jpg",
            image3: "/images/1611420827926.jpg",
            image4: "/images/1611420831118.jpg",
            image5: "/images/1611420834226.jpg",
            price: 129,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "new",
            brand: "first-brand",
            countInStock: 5,
            deliveryTime: "1-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product B",
            image: "/images/1611421179217.jpg",
            image2: "/images/1611421151983.jpg",
            image3: "/images/1611421155605.jpg",
            image4: "/images/1611421158242.jpg",
            image5: "/images/1611421162407.jpg",
            price: 100,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 3,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It is a longer example title of product C",
            image: "/images/1611421354089.jpg",
            image2: "/images/1611421366552.jpg",
            image3: "/images/1611421375286.jpg",
            image4: "/images/1611421378456.jpg",
            image5: "/images/1611421381200.jpg",
            price: 59,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "new",
            brand: "third-brand",
            countInStock: 9,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product D",
            image: "/images/1611421653057.jpg",
            image2: "/images/1611421634955.jpg",
            image3: "/images/1611421638312.jpg",
            image4: "/images/1611421641497.jpg",
            image5: "/images/1611421645898.jpg",
            price: 399,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 3,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It is a longer example title of product E",
            image: "/images/1611421765346.jpg",
            image2: "/images/1611421776324.jpg",
            image3: "/images/1611421780064.jpg",
            image4: "/images/1611421784236.jpg",
            image5: "/images/1611421790310.jpg",
            price: 8,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 4,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It is a longer example title of product F",
            image: "/images/1611421915158.jpg",
            image2: "/images/1611421927128.jpg",
            image3: "/images/1611421932522.jpg",
            image4: "/images/1611421936131.jpg",
            image5: "/images/1611421939547.jpg",
            price: 259,
            category: "first-category",
            subcategory: "st-first-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 19,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It is a longer example title of product G",
            image: "/images/1611422129029.jpg",
            image2: "/images/1611422142454.jpg",
            image3: "/images/1611422146153.jpg",
            image4: "/images/1611422150111.jpg",
            image5: "/images/1611422152296.jpg",
            price: 10,
            category: "first-category",
            subcategory: "st-second-subcategory",
            tag: "",
            brand: "third-brand",
            countInStock: 10,
            deliveryTime: "4-5 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product H",
            image: "/images/1611422278922.jpg",
            image2: "/images/1611422323573.jpg",
            image3: "/images/1611422328538.jpg",
            image4: "/images/1611422333060.jpg",
            image5: "/images/1611422337100.jpg",
            price: 139,
            category: "first-category",
            subcategory: "st-third-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 8,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product I",
            image: "/images/1611422546019.jpg",
            image2: "/images/1611422580442.jpg",
            image3: "/images/1611422585035.jpg",
            image4: "/images/1611422588290.jpg",
            image5: "/images/1611422591659.jpg",
            price: 299,
            category: "first-category",
            subcategory: "st-third-subcategory",
            tag: "new",
            brand: "fourth-brand",
            countInStock: 15,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product J",
            image: "/images/1611422680358.jpg",
            image2: "/images/1611422634060.jpg",
            image3: "/images/1611422637271.jpg",
            image4: "/images/1611422642075.jpg",
            image5: "/images/1611422644464.jpg",
            price: 99,
            category: "first-category",
            subcategory: "st-third-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 12,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product K",
            image: "/images/1611422963906.jpg",
            image2: "/images/1611422988442.jpg",
            image3: "/images/1611422993509.jpg",
            image4: "/images/1611422996559.jpg",
            image5: "/images/1611423000432.jpg",
            price: 159,
            category: "first-category",
            subcategory: "st-second-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 12,
            deliveryTime: "4-5 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product M",
            image: "/images/1611423191012.jpg",
            image2: "/images/1611423088830.jpg",
            image3: "/images/1611423092755.jpg",
            image4: "/images/1611423095717.jpg",
            image5: "/images/1611423100740.jpg",
            price: 199,
            category: "first-category",
            subcategory: "st-second-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 6,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product N",
            image: "/images/1611423349438.jpg",
            image2: "/images/1611423361984.jpg",
            image3: "/images/1611423366500.jpg",
            image4: "/images/1611423369652.jpg",
            image5: "/images/1611423377866.jpg",
            price: 259,
            category: "second-category",
            subcategory: "nd-third-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 14,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product O",
            image: "/images/1611423780924.jpg",
            image2: "/images/1611423812469.jpg",
            image3: "/images/1611423817256.jpg",
            image4: "/images/1611423823487.jpg",
            image5: "/images/1611423825501.jpg",
            price: 49,
            category: "second-category",
            subcategory: "nd-third-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 14,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product P",
            image: "/images/1611423944921.jpg",
            image2: "/images/1611423919277.jpg",
            image3: "/images/1611423922577.jpg",
            image4: "/images/1611423925231.jpg",
            image5: "/images/1611423928388.jpg",
            price: 149,
            category: "second-category",
            subcategory: "nd-third-subcategory",
            tag: "new",
            brand: "fifth-brand",
            countInStock: 10,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product R",
            image: "/images/1611424247182.jpg",
            image2: "/images/1611424260290.jpg",
            image3: "/images/1611424264431.jpg",
            image4: "/images/1611424267071.jpg",
            image5: "/images/1611424269507.jpg",
            price: 39,
            category: "second-category",
            subcategory: "nd-second-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 5,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product S",
            image: "/images/1611424488875.jpg",
            image2: "/images/1611424498150.jpg",
            image3: "/images/1611424502392.jpg",
            image4: "/images/1611424505285.jpg",
            image5: "/images/1611424508671.jpg",
            price: 199,
            category: "second-category",
            subcategory: "nd-second-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 12,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product T",
            image: "/images/1611424600073.jpg",
            image2: "/images/1611424610532.jpg",
            image3: "/images/1611424614304.jpg",
            image4: "/images/1611424618580.jpg",
            image5: "/images/1611424623329.jpg",
            price: 159,
            category: "second-category",
            subcategory: "nd-second-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 4,
            deliveryTime: "1-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product AB",
            image: "/images/1611503381369.jpg",
            image2: "/images/1611503406474.jpg",
            image3: "/images/1611503419281.jpg",
            image4: "/images/1611503426913.jpg",
            image5: "/images/1611503435188.jpg",
            price: 299,
            category: "second-category",
            subcategory: "nd-first-subcategory",
            tag: "",
            brand: "third-brand",
            countInStock: 2,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product BB",
            image: "/images/1611503483076.jpg",
            image2: "/images/1611503496175.jpg",
            image3: "/images/1611503499797.jpg",
            image4: "/images/1611503508031.jpg",
            image5: "/images/1611503511208.jpg",
            price: 129,
            category: "second-category",
            subcategory: "nd-first-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 12,
            deliveryTime: "4-5 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product AC",
            image: "/images/1611503665262.jpg",
            image2: "/images/1611503678910.jpg",
            image3: "/images/1611503689054.jpg",
            image4: "/images/1611503691486.jpg",
            image5: "/images/1611503696948.jpg",
            price: 100,
            category: "second-category",
            subcategory: "nd-first-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 139,
            deliveryTime: "1-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product AD",
            image: "/images/1611503862326.jpg",
            image2: "/images/1611503887966.jpg",
            image3: "/images/1611503895060.jpg",
            image4: "/images/1611503897875.jpg",
            image5: "/images/1611503902287.jpg",
            price: 99,
            category: "third-category",
            subcategory: "rd-first-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 20,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product AE",
            image: "/images/1611504014548.jpg",
            image2: "/images/1611504026394.jpg",
            image3: "/images/1611504031892.jpg",
            image4: "/images/1611504035600.jpg",
            image5: "/images/1611504041299.jpg",
            price: 199,
            category: "third-category",
            subcategory: "rd-first-subcategory",
            tag: "",
            brand: "fourth-brand",
            countInStock: 0,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product BD",
            image: "/images/1611504183534.jpg",
            image2: "/images/1611504193008.jpg",
            image3: "/images/1611504198579.jpg",
            image4: "/images/1611504204231.jpg",
            image5: "/images/1611504211076.jpg",
            price: 599,
            category: "third-category",
            subcategory: "rd-first-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 10,
            deliveryTime: "2-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product BF",
            image: "/images/1611504824043.jpg",
            image2: "/images/1611504837009.jpg",
            image3: "/images/1611504845948.jpg",
            image4: "/images/1611504849827.jpg",
            image5: "/images/1611504853262.jpg",
            price: 299,
            category: "third-category",
            subcategory: "rd-second-subcategory",
            tag: "",
            brand: "third-brand",
            countInStock: 8,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product BG",
            image: "/images/1611504941568.jpg",
            image2: "/images/1611504953537.jpg",
            image3: "/images/1611504960134.jpg",
            image4: "/images/1611504972947.jpg",
            image5: "/images/1611504975341.jpg",
            price: 199,
            category: "third-category",
            subcategory: "rd-second-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 0,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product BH",
            image: "/images/1611505098099.jpg",
            image2: "/images/1611505106735.jpg",
            image3: "/images/1611505109296.jpg",
            image4: "/images/1611505113676.jpg",
            image5: "/images/1611505117555.jpg",
            price: 49,
            category: "third-category",
            subcategory: "rd-second-subcategory",
            tag: "",
            brand: "fourth-brand",
            countInStock: 4,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product CD",
            image: "/images/1611505257662.jpg",
            image2: "/images/1611505264846.jpg",
            image3: "/images/1611505267374.jpg",
            image4: "/images/1611505269961.jpg",
            image5: "/images/1611505271841.jpg",
            price: 29,
            category: "third-category",
            subcategory: "rd-third-subcategory",
            tag: "",
            brand: "third-brand",
            countInStock: 0,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product CA",
            image: "/images/1611505392008.jpg",
            image2: "/images/1611505416603.jpg",
            image3: "/images/1611505419502.jpg",
            image4: "/images/1611505423698.jpg",
            image5: "/images/1611505429264.jpg",
            price: 99,
            category: "third-category",
            subcategory: "rd-third-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 8,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product cm",
            image: "/images/1611505524531.jpg",
            image2: "/images/1611505529929.jpg",
            image3: "/images/1611505534451.jpg",
            image4: "/images/1611505536582.jpg",
            image5: "/images/1611505539090.jpg",
            price: 69,
            category: "third-category",
            subcategory: "rd-third-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 0,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product VB",
            image: "/images/1611505613988.jpg",
            image2: "/images/1611505622837.jpg",
            image3: "/images/1611505625945.jpg",
            image4: "/images/1611505629365.jpg",
            image5: "/images/1611505631428.jpg",
            price: 189,
            category: "fourth-category",
            subcategory: "th-first-subcategory",
            tag: "new",
            brand: "third-brand",
            countInStock: 6,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product DA",
            image: "/images/1611505801477.jpg",
            image2: "/images/1611505820393.jpg",
            image3: "/images/1611505824540.jpg",
            image4: "/images/1611505834315.jpg",
            image5: "/images/1611505836650.jpg",
            price: 299,
            category: "fourth-category",
            subcategory: "th-first-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 299,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product DE",
            image: "/images/1611505948185.jpg",
            image2: "/images/1611505954464.jpg",
            image3: "/images/1611505957112.jpg",
            image4: "/images/1611505961212.jpg",
            image5: "/images/1611505966394.jpg",
            price: 149,
            category: "fourth-category",
            subcategory: "th-first-subcategory",
            tag: "",
            brand: "fifth-brand",
            countInStock: 12,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product FA",
            image: "/images/1611506124861.jpg",
            image2: "/images/1611506133554.jpg",
            image3: "/images/1611506138054.jpg",
            image4: "/images/1611506142114.jpg",
            image5: "/images/1611506147020.jpg",
            price: 99,
            category: "fourth-category",
            subcategory: "th-second-subcategory",
            tag: "new",
            brand: "second-brand",
            countInStock: 20,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product GB",
            image: "/images/1611506289138.jpg",
            image2: "/images/1611506299317.jpg",
            image3: "/images/1611506306369.jpg",
            image4: "/images/1611506303088.jpg",
            image5: "/images/1611506309060.jpg",
            price: 129,
            category: "fourth-category",
            subcategory: "th-second-subcategory",
            tag: "",
            brand: "fourth-brand",
            countInStock: 8,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product HJ",
            image: "/images/1611506407901.jpg",
            image2: "/images/1611506413880.jpg",
            image3: "/images/1611506416168.jpg",
            image4: "/images/1611506422278.jpg",
            image5: "/images/1611506425403.jpg",
            price: 199,
            category: "fourth-category",
            subcategory: "th-second-subcategory",
            tag: "new",
            brand: "third-brand",
            countInStock: 0,
            deliveryTime: "4-5 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Example title of product NM",
            image: "/images/1611506695488.jpg",
            image2: "/images/1611506706096.jpg",
            image3: "/images/1611506710120.jpg",
            image4: "/images/1611506713077.jpg",
            image5: "/images/1611506716447.jpg",
            price: 399,
            category: "fourth-category",
            subcategory: "th-third-subcategory",
            tag: "",
            brand: "first-brand",
            countInStock: 12,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "Super long long long long long example title of product KL",
            image: "/images/1611506842277.jpg",
            image2: "/images/1611506875143.jpg",
            image3: "/images/1611506878669.jpg",
            image4: "/images/1611506881268.jpg",
            image5: "/images/1611506885639.jpg",
            price: 259,
            category: "fourth-category",
            subcategory: "th-third-subcategory",
            tag: "",
            brand: "second-brand",
            countInStock: 8,
            deliveryTime: "1-3 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }, {
            name: "It's a longer example title of product PM",
            image: "/images/1611507004563.jpg",
            image2: "/images/1611507011253.jpg",
            image3: "/images/1611507015354.jpg",
            image4: "/images/1611507018044.jpg",
            image5: "/images/1611507024126.jpg",
            price: 99,
            category: "fourth-category",
            subcategory: "th-third-subcategory",
            tag: "new",
            brand: "first-brand",
            countInStock: 10,
            deliveryTime: "1-2 work days",
            rating: 0,
            numReviews: 0,
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
        }
    ],
    advertisingBoxes: [
        {
            name: "advertising_1",
            link: "/",
            image: "/images/1611507310441.jpg"
        }, {
            name: "advertising_2",
            link: "/",
            image: "/images/1611507340890.jpg"
        }, {
            name: "advertising_3",
            link: "/",
            image: "/images/1611507356761.jpg"
        }, {
            name: "advertising_4",
            link: "/",
            image: "/images/1611507368896.jpg"
        }
    ],
    banners: [
        {
            name: "banner_6",
            image: "/images/1611513306783.jpg",
            link: "/",
            category: "home"
        }, {
            name: "banner_1",
            image: "/images/1611513603637.jpg",
            link: "/",
            category: "third-category"
        }, {
            name: "banner_2",
            image: "/images/1611514602280.jpg",
            link: "/",
            category: "",
            subcategory: "/th-first-subcategory"
        }, {
            name: "banner_3",
            image: "/images/1611514680349.jpg",
            link: "/",
            category: "second-category"
        }, {
            name: "banner_4",
            image: "/images/1611514845936.jpg",
            link: "/",
            category: "fourth-category"
        }, {
            name: "banner_5",
            image: "/images/1611514890330.jpg",
            link: "/",
            category: "first-category"
        }
    ],
    covers: [
        {
            name: "cover_1",
            link: "/",
            image: "/images/1611507127529.jpg"
        }, {
            name: "cover_2",
            link: "/",
            image: "/images/1611507229577.jpg"
        }, {
            name: "cover_3",
            link: "/",
            image: "/images/1611507238733.jpg"
        }
    ],
    recommendedCategories: [
        {
            name: "category_box_1",
            link: "/products/first-category",
            image: "/images/1611507418796.jpg"
        }, {
            name: "category_box_2",
            link: "/products/second-category",
            image: "/images/1611507453560.jpg"
        }, {
            name: "category_box_3",
            link: "/products/third-category",
            image: "/images/1611507493211.jpg"
        }, {
            name: "category_box_4",
            link: "/products/fourth-category",
            image: "/images/1611507549635.jpg"
        }
    ],
    infoBoxes: [
        {
            title: "First title info box",
            text: "First text info box",
            link: "/",
            image: "/images/1612372739820.jpg",
            name: "first"
        }, {
            title: "Second title info box",
            text: "Second text info box",
            link: "/",
            image: "/images/1612372907086.jpg",
            name: "firsta"
        }, {
            title: "Third title info box",
            text: "Third text info box",
            link: "/",
            image: "/images/1612372925273.jpg",
            name: "firsts"
        }, {
            title: "Fourth title info box",
            text: "Fourth text info box",
            link: "/",
            image: "/images/1612372937220.jpg",
            name: "firstd"
        }, {
            title: "Fifth title info box",
            text: "Fifth text info box",
            link: "/",
            image: "/images/1612372946182.jpg",
            name: "firstf"
        }
    ],
    contactForms: [
        {
            name: "Kamil",
            email: "test@test.com",
            title: "Test",
            text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        }
    ]
}


export default data;