export const ADVERTISING_BOX_LIST_REQUEST = 'ADVERTISING_BOX_LIST_REQUEST';
export const ADVERTISING_BOX_LIST_SUCCESS = 'ADVERTISING_BOX_LIST_SUCCESS';
export const ADVERTISING_BOX_LIST_FAIL = 'ADVERTISING_BOX_LIST_FAIL';

export const ADVERTISING_BOX_DETAILS_REQUEST = 'ADVERTISING_BOX_DETAILS_REQUEST';
export const ADVERTISING_BOX_DETAILS_SUCCESS = 'ADVERTISING_BOX_DETAILS_SUCCESS';
export const ADVERTISING_BOX_DETAILS_FAIL = 'ADVERTISING_BOX_DETAILS_FAIL';

export const ADVERTISING_BOX_CREATE_REQUEST = 'ADVERTISING_BOX_CREATE_REQUEST';
export const ADVERTISING_BOX_CREATE_SUCCESS = 'ADVERTISING_BOX_CREATE_SUCCESS';
export const ADVERTISING_BOX_CREATE_FAIL = 'ADVERTISING_BOX_CREATE_FAIL';
export const ADVERTISING_BOX_CREATE_RESET = 'ADVERTISING_BOX_CREATE_RESET';

export const ADVERTISING_BOX_UPDATE_REQUEST = 'ADVERTISING_BOX_UPDATE_REQUEST';
export const ADVERTISING_BOX_UPDATE_SUCCESS = 'ADVERTISING_BOX_UPDATE_SUCCESS';
export const ADVERTISING_BOX_UPDATE_FAIL = 'ADVERTISING_BOX_UPDATE_FAIL';
export const ADVERTISING_BOX_UPDATE_RESET = 'ADVERTISING_BOX_UPDATE_RESET';

export const ADVERTISING_BOX_DELETE_REQUEST = 'ADVERTISING_BOX_DELETE_REQUEST';
export const ADVERTISING_BOX_DELETE_SUCCESS = 'ADVERTISING_BOX_DELETE_SUCCESS';
export const ADVERTISING_BOX_DELETE_FAIL = 'ADVERTISING_BOX_DELETE_FAIL';
export const ADVERTISING_BOX_DELETE_RESET = 'ADVERTISING_BOX_DELETE_RESET';