export const CONTACTFORM_LIST_REQUEST = 'CONTACTFORM_LIST_REQUEST';
export const CONTACTFORM_LIST_SUCCESS = 'CONTACTFORM_LIST_SUCCESS';
export const CONTACTFORM_LIST_FAIL = 'CONTACTFORM_LIST_FAIL';

export const CONTACTFORM_MINE_LIST_REQUEST = 'CONTACTFORM_MINE_LIST_REQUEST';
export const CONTACTFORM_MINE_LIST_SUCCESS = 'CONTACTFORM_MINE_LIST_SUCCESS';
export const CONTACTFORM_MINE_LIST_FAIL = 'CONTACTFORM_MINE_LIST_FAIL';

export const CONTACTFORM_DETAILS_REQUEST = 'CONTACTFORM_DETAILS_REQUEST';
export const CONTACTFORM_DETAILS_SUCCESS = 'CONTACTFORM_DETAILS_SUCCESS';
export const CONTACTFORM_DETAILS_FAIL = 'CONTACTFORM_DETAILS_FAIL';

export const CONTACTFORM_CREATE_REQUEST = 'CONTACTFORM_CREATE_REQUEST';
export const CONTACTFORM_CREATE_SUCCESS = 'CONTACTFORM_CREATE_SUCCESS';
export const CONTACTFORM_CREATE_FAIL = 'CONTACTFORM_CREATE_FAIL';
export const CONTACTFORM_CREATE_RESET = 'CONTACTFORM_CREATE_RESET';

export const CONTACTFORM_DELETE_REQUEST = 'CONTACTFORM_DELETE_REQUEST';
export const CONTACTFORM_DELETE_SUCCESS = 'CONTACTFORM_DELETE_SUCCESS';
export const CONTACTFORM_DELETE_FAIL = 'CONTACTFORM_DELETE_FAIL';
export const CONTACTFORM_DELETE_RESET = 'CONTACTFORM_DELETE_RESET';