export const COVER_LIST_REQUEST = 'COVER_LIST_REQUEST';
export const COVER_LIST_SUCCESS = 'COVER_LIST_SUCCESS';
export const COVER_LIST_FAIL = 'COVER_LIST_FAIL';

export const COVER_DETAILS_REQUEST = 'COVER_DETAILS_REQUEST';
export const COVER_DETAILS_SUCCESS = 'COVER_DETAILS_SUCCESS';
export const COVER_DETAILS_FAIL = 'COVER_DETAILS_FAIL';

export const COVER_CREATE_REQUEST = 'COVER_CREATE_REQUEST';
export const COVER_CREATE_SUCCESS = 'COVER_CREATE_SUCCESS';
export const COVER_CREATE_FAIL = 'COVER_CREATE_FAIL';
export const COVER_CREATE_RESET = 'COVER_CREATE_RESET';

export const COVER_UPDATE_REQUEST = 'COVER_UPDATE_REQUEST';
export const COVER_UPDATE_SUCCESS = 'COVER_UPDATE_SUCCESS';
export const COVER_UPDATE_FAIL = 'COVER_UPDATE_FAIL';
export const COVER_UPDATE_RESET = 'COVER_UPDATE_RESET';

export const COVER_DELETE_REQUEST = 'COVER_DELETE_REQUEST';
export const COVER_DELETE_SUCCESS = 'COVER_DELETE_SUCCESS';
export const COVER_DELETE_FAIL = 'COVER_DELETE_FAIL';
export const COVER_DELETE_RESET = 'COVER_DELETE_RESET';