export const INFOBOX_LIST_REQUEST = 'INFOBOX_LIST_REQUEST';
export const INFOBOX_LIST_SUCCESS = 'INFOBOX_LIST_SUCCESS';
export const INFOBOX_LIST_FAIL = 'INFOBOX_LIST_FAIL';

export const INFOBOX_DETAILS_REQUEST = 'INFOBOX_DETAILS_REQUEST';
export const INFOBOX_DETAILS_SUCCESS = 'INFOBOX_DETAILS_SUCCESS';
export const INFOBOX_DETAILS_FAIL = 'INFOBOX_DETAILS_FAIL';

export const INFOBOX_CREATE_REQUEST = 'INFOBOX_CREATE_REQUEST';
export const INFOBOX_CREATE_SUCCESS = 'INFOBOX_CREATE_SUCCESS';
export const INFOBOX_CREATE_FAIL = 'INFOBOX_CREATE_FAIL';
export const INFOBOX_CREATE_RESET = 'INFOBOX_CREATE_RESET';

export const INFOBOX_UPDATE_REQUEST = 'INFOBOX_UPDATE_REQUEST';
export const INFOBOX_UPDATE_SUCCESS = 'INFOBOX_UPDATE_SUCCESS';
export const INFOBOX_UPDATE_FAIL = 'INFOBOX_UPDATE_FAIL';
export const INFOBOX_UPDATE_RESET = 'INFOBOX_UPDATE_RESET';

export const INFOBOX_DELETE_REQUEST = 'INFOBOX_DELETE_REQUEST';
export const INFOBOX_DELETE_SUCCESS = 'INFOBOX_DELETE_SUCCESS';
export const INFOBOX_DELETE_FAIL = 'INFOBOX_DELETE_FAIL';
export const INFOBOX_DELETE_RESET = 'INFOBOX_DELETE_RESET';