export const NEWSLETTER_LIST_REQUEST = 'NEWSLETTER_LIST_REQUEST';
export const NEWSLETTER_LIST_SUCCESS = 'NEWSLETTER_LIST_SUCCESS';
export const NEWSLETTER_LIST_FAIL = 'NEWSLETTER_LIST_FAIL';

export const NEWSLETTER_DETAILS_REQUEST = 'NEWSLETTER_DETAILS_REQUEST';
export const NEWSLETTER_DETAILS_SUCCESS = 'NEWSLETTER_DETAILS_SUCCESS';
export const NEWSLETTER_DETAILS_FAIL = 'NEWSLETTER_DETAILS_FAIL';

export const NEWSLETTER_CREATE_REQUEST = 'NEWSLETTER_CREATE_REQUEST';
export const NEWSLETTER_CREATE_SUCCESS = 'NEWSLETTER_CREATE_SUCCESS';
export const NEWSLETTER_CREATE_FAIL = 'NEWSLETTER_CREATE_FAIL';
export const NEWSLETTER_CREATE_RESET = 'NEWSLETTER_CREATE_RESET';

export const NEWSLETTER_DELETE_REQUEST = 'NEWSLETTER_DELETE_REQUEST';
export const NEWSLETTER_DELETE_SUCCESS = 'NEWSLETTER_DELETE_SUCCESS';
export const NEWSLETTER_DELETE_FAIL = 'NEWSLETTER_DELETE_FAIL';
export const NEWSLETTER_DELETE_RESET = 'NEWSLETTER_DELETE_RESET';