export const RECOMMENDED_CATEGORY_LIST_REQUEST = 'RECOMMENDED_CATEGORY_LIST_REQUEST';
export const RECOMMENDED_CATEGORY_LIST_SUCCESS = 'RECOMMENDED_CATEGORY_LIST_SUCCESS';
export const RECOMMENDED_CATEGORY_LIST_FAIL = 'RECOMMENDED_CATEGORY_LIST_FAIL';

export const RECOMMENDED_CATEGORY_DETAILS_REQUEST = 'RECOMMENDED_CATEGORY_DETAILS_REQUEST';
export const RECOMMENDED_CATEGORY_DETAILS_SUCCESS = 'RECOMMENDED_CATEGORY_DETAILS_SUCCESS';
export const RECOMMENDED_CATEGORY_DETAILS_FAIL = 'RECOMMENDED_CATEGORY_DETAILS_FAIL';

export const RECOMMENDED_CATEGORY_CREATE_REQUEST = 'RECOMMENDED_CATEGORY_CREATE_REQUEST';
export const RECOMMENDED_CATEGORY_CREATE_SUCCESS = 'RECOMMENDED_CATEGORY_CREATE_SUCCESS';
export const RECOMMENDED_CATEGORY_CREATE_FAIL = 'RECOMMENDED_CATEGORY_CREATE_FAIL';
export const RECOMMENDED_CATEGORY_CREATE_RESET = 'RECOMMENDED_CATEGORY_CREATE_RESET';

export const RECOMMENDED_CATEGORY_UPDATE_REQUEST = 'RECOMMENDED_CATEGORY_UPDATE_REQUEST';
export const RECOMMENDED_CATEGORY_UPDATE_SUCCESS = 'RECOMMENDED_CATEGORY_UPDATE_SUCCESS';
export const RECOMMENDED_CATEGORY_UPDATE_FAIL = 'RECOMMENDED_CATEGORY_UPDATE_FAIL';
export const RECOMMENDED_CATEGORY_UPDATE_RESET = 'RECOMMENDED_CATEGORY_UPDATE_RESET';

export const RECOMMENDED_CATEGORY_DELETE_REQUEST = 'RECOMMENDED_CATEGORY_DELETE_REQUEST';
export const RECOMMENDED_CATEGORY_DELETE_SUCCESS = 'RECOMMENDED_CATEGORY_DELETE_SUCCESS';
export const RECOMMENDED_CATEGORY_DELETE_FAIL = 'RECOMMENDED_CATEGORY_DELETE_FAIL';
export const RECOMMENDED_CATEGORY_DELETE_RESET = 'RECOMMENDED_CATEGORY_DELETE_RESET';